### ISSUE TITLE
App crashes when trying to redeploy

### ISSUE THREAD

**Issue by bendaf** [SimonVT/schematic#70]
I can run the app from android studio only if I do a rebuild first, because the simple deploy crashes: 
      `java.lang.RuntimeException: Unable to get provider      hu.bendaf.udacity.popularmovies.popularmoviesapp.data.generated.MovieProvider: java.lang.ClassNotFoundException: Didn't find class "hu.bendaf.udacity.popularmovies.popularmoviesapp.data.generated.MovieProvider" on path: DexPathList[[zip file "/data/app/hu.bendaf.udacity.popularmovies.popularmoviesapp-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]`

Here is my app: 
https://github.com/bendaf/PopularMoviesApp

I am using samsung galaxy s3 with API level 21. 
Am I doing something wrong?

**Comment by bendaf** [comment]
I have also tried it with a Pixel C, API level 25. The same issue happens: if I modify the code (add a log somewhere for example) and redeploy the code before cleaning the project the app crashes on startup with the same log: 
`02-08 11:37:26.896 27274-27274/hu.bendaf.udacity.popularmovies.popularmoviesapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                  Process: hu.bendaf.udacity.popularmovies.popularmoviesapp, PID: 27274
                                                                                                  java.lang.RuntimeException: Unable to get provider hu.bendaf.udacity.popularmovies.popularmoviesapp.data.generated.MovieProvider: java.lang.ClassNotFoundException: Didn't find class "hu.bendaf.udacity.popularmovies.popularmoviesapp.data.generated.MovieProvider" on path: DexPathList[[zip file "/data/app/hu.bendaf.udacity.popularmovies.popularmoviesapp-2/base.apk"],nativeLibraryDirectories=[/data/app/hu.bendaf.udacity.popularmovies.popularmoviesapp-2/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                                                      at android.app.ActivityThread.installProvider(ActivityThread.java:5856)
                                                                                                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:5445)
                                                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384)
                                                                                                      at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "hu.bendaf.udacity.popularmovies.popularmoviesapp.data.generated.MovieProvider" on path: DexPathList[[zip file "/data/app/hu.bendaf.udacity.popularmovies.popularmoviesapp-2/base.apk"],nativeLibraryDirectories=[/data/app/hu.bendaf.udacity.popularmovies.popularmoviesapp-2/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                      at android.app.ActivityThread.installProvider(ActivityThread.java:5841)
                                                                                                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:5445) 
                                                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384) 
                                                                                                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                      at android.os.Looper.loop(Looper.java:154) 
                                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                                      at java.lang.reflect.Method.invoke(Native Method) `

Am I doing something wrong in the database?

**Comment by MyDogTom** [comment]
@bendaf It is not related to this library. StackOverflow is definitely more appropriate place for such questions.
In order to find the cause for your crash I would first disable jack and disable InstantRun (in case you use it).

**Comment by bendaf** [comment]
Thanks, I thought because the generated class is not found the problem will be with the library. I will ask on stackoverflow than!

**Comment by SimonVT** [comment]
Yeah, likely related to jack. Will probably be fixed before it's stable.

**Comment by bendaf** [comment]
It was, indeed jack! Thanks for the help.
