### ISSUE TITLE
Unable to get provider error

### ISSUE THREAD

**Issue by kartikmishra** [SimonVT/schematic#89]
In my android manifest file I have declared the name of provider right but still its giving me the error that unable to get provider-

 Process: android.example.com.squawker, PID: 17946
                  java.lang.RuntimeException: Unable to get provider android.example.com.squawker.provider.generated.SquawkProvider: java.lang.ClassNotFoundException: Didn't find class "android.example.com.squawker.provider.generated.SquawkProvider" on path: DexPathList[[zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/base.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_dependencies_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_resources_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_0_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_1_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_2_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_3_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_4_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_5_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_6_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_7_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_8_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/lib/x86, /system/lib, /vendor/lib]]
                      at android.app.ActivityThread.installProvider(ActivityThread.java:6242)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
                      at android.app.ActivityThread.-wrap1(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.example.com.squawker.provider.generated.SquawkProvider" on path: DexPathList[[zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/base.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_dependencies_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_resources_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_0_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_1_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_2_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_3_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_4_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_5_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_6_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_7_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_8_apk.apk", zip file "/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/android.example.com.squawker-ynS3Get5niOQGQR2P2TtcA==/lib/x86, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at android.app.ActivityThread.installProvider(ActivityThread.java:6227)
                      	... 10 more
                  	Suppressed: java.io.IOException: No original dex files found for dex location /data/a

**Comment by zoxerus** [comment]
check this out:
https://stackoverflow.com/a/47384765/5950528

**Comment by mayarkhaled** [comment]
I check this https://stackoverflow.com/a/47384765/5950528 and I have same problem !

**Comment by mayarkhaled** [comment]
> check this out:
> https://stackoverflow.com/a/47384765/5950528

still have same problem

**Comment by Adarsh-K** [comment]
> check this out:
> https://stackoverflow.com/a/47384765/5950528

This works Thanks
